branch-defaults:
  master:
    environment: Tuber-dev
environment-defaults:
  Tuber-dev:
    branch: null
    repository: null
global:
  application_name: Tuber
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.3.1 running Python 2.7
  default_region: us-west-1
  profile: eb-cli
  sc: git
